config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'projects/index'

  get 'projects/new'

  get 'projects/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks

  accepts_nested_attributes_for :tasks, allow_destroy: true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :tasks, inverse_of: :project

  accepts_nested_attributes_for :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
  end

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(allowed_params)
    if @project.save
      flash[:notice] = 'Successfully created project.'
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(allowed_params)
      redirect_to @project, notice: 'Successfully updated project'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = 'Successfully destoryed project.'
      redirect_to projects_path
    else
      render :show
    end
  end

  private

  def allowed_params
    params.require(:project).permit(:name, tasks_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<% @project = Project.find(params[:id]) %>
<%= form_for @project do |f| %>
  <p>
    Name: <%= f.text_field :name %>
  </p>
  <%= f.fields_for :tasks do |task_form| %>
    <p>
      Task: <%= task_form.text_field :name %>
      <%= task_form.check_box :_destroy %>
      <%= task_form.label :_destroy, "Remove Task" %>
    </p>
  <% end %>
  <p>
    <%= f.submit 'Update Project' %>
  </p>
<% end %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <% for task in project.tasks %>
          <td><%= task.name %><td>
        <% end %>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for @project do |f| %>
  <p>
    Name: <%= f.text_field :name %>
  </p>

  <%= select_tag "quantity", options_for_select((1..4),1), :onchange => 'changed(this)' %>

  <% 4.times do |i| %>
    <%= f.fields_for :tasks, Task.new do |task_form| %>
      <p id="<%= i.to_s %>">
          Task: <%= task_form.text_field :name %>
      </p>
    <% end %>
  <% end %>
  <p>
    <%= f.submit 'Create Project' %>
  </p>
<% end %>

<script>

  for (var i = 0; i < 3; i++) {
    document.getElementById(i.toString()).style.display = 'none';
  }

  function changed(sel) {
    var taskNum = sel.options[sel.selectedIndex].value;
    for (var i = 3; i >= 0; i--) {
      if (taskNum <= i) {
        document.getElementById(i.toString()).style.display = 'none';
      } else {
        document.getElementById(i.toString()).style.display = 'block';
      }
    }
  }
</script>

app/views/projects/show.html.erb
<h1>Show Project</h1>
<% @project = Project.find(params[:id]) %>
<p>
  <strong>Project:</strong>
  <%= @project.name %>
</p>
<% for task in @project.tasks %>
  <p>
    <strong>Task:</strong>
    <%= task.name %>
  </p>
<% end %>